### ISSUE TITLE
what time can be support Hessian Codec 

### ISSUE THREAD

**Issue by golangpkg** [dubbo/go-for-apache-dubbo#3]
what time can be support Hessian Codec 

I want use golang to call java Provider . but defualt Codec  is Hessian  not support .

**Comment by AlexStocks** [comment]
The Hessian Codec has been written in my private github repo dubbogo(https://github.com/alexstocks/dubbogo/blob/master/codec/hessian/codec.go). I will start the hessian feature for dubbo-go after National Day.  Maybe you have to wait for about 2 months.

**Comment by golangpkg** [comment]
oh , I found , thank you .
