### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by MuFe** [dubbo/go-for-apache-dubbo#50]
github.com/dubbo/go-for-apache-dubbo/dubbo/client.go:237:21: undefined: hessian.Heartbeat

**Comment by fangyincheng** [comment]
> github.com/dubbo/go-for-apache-dubbo/dubbo/client.go:237:21: undefined: hessian.Heartbeat

Is your version of Hessian 2 different from version in go.mod?
Try to run ```go mod tidy```

**Comment by AlexStocks** [comment]
@MuFe Are u interested in joining the dubbogo develop team?

**Comment by AlexStocks** [comment]
@MuFe Are u interested in joining the dubbogo develop team? If so, please send a email to me ( alexstofcks at foxmail dot com ) to contact with me.

**Comment by hxmhlt** [comment]
@MuFe Hi，Does your issue has been resolved?

**Comment by hxmhlt** [comment]
@MuFe If there is no problem, I will close the issue. If there is still have  problem, you can open it at any time.
