### ISSUE TITLE
go-server启动后不能访问

### ISSUE THREAD

**Issue by chenleirr** [dubbo/go-for-apache-dubbo#52]
**go-server启动service后，启动go-client。但是client报错**：
panic: Failed to invoke the method GetUser in the service 

(2/1)from the registry zookeeper://:@127.0.0.1:2181?group=&registry=zookeeper&registry.role=0&registry.timeout=3s on the consumer 192.168.99.1 using the dubbo version 2.5.3. Last error is can not find go type name  in registry.

**在zookeeper里有这个service**：

[zk: localhost:2181(CONNECTED) 76] ls /dubbo/com.lagou.chenlei.demo.main.UserService/providers
[dubbo://10.71.8.99:12345/com.xxx.demo.main.UserService?anyhost=true&app.version=1.0&application=BDTService&category=providers&cluster=failover&dubbo=dubbo-provider-golang-2.5.3&environment=dev&group=&interface=com.xxx.demo.main.UserService&ip=192.168.99.1&loadbalance=random&methods.GetUser.loadbalance=&methods.GetUser.retries=0&methods.GetUser.weight=0&module=dubbogo+user-info+server&name=BDTService&organization=ikurento.com&owner=ZX&pid=59371&retries=0&side=provider&timestamp=1558520537&version=&warmup=100]

**Comment by hxmhlt** [comment]
@chenleirr  using the dubbo version 2.5.3.这个版本好像有点问题，你这个版本号是自己改过吗？

**Comment by hxmhlt** [comment]
@chenleirr 请问你用的是哪次提交的代码

**Comment by chenleirr** [comment]
@hxmhlt   我改为2.6.0也有这个问题：can not find go type name  in registry

启动go-server后，我另起java consumer能调用通了，但是go-client调用还是会报这个错误

**Comment by chenleirr** [comment]
@hxmhlt  昨天develop分支的代码

**Comment by fangyincheng** [comment]
@chenleirr 你的代码是用examples还是自己修改过的？你的struct是不是没用执行图片的方法？
![image](https://user-images.githubusercontent.com/18375310/58226955-74685000-7d5b-11e9-97c6-27bdcd8b87b9.png)

**Comment by hxmhlt** [comment]
@chenleirr 如果方便可以进钉钉群，群号 : 23331795。详细讨论你的问题。

**Comment by chenleirr** [comment]
@hxmhlt @fangyincheng 感谢两位，这个问题应该是我yml文件格式的问题。重新pull可以了
